import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  Linking,
} from 'react-native';
import { colors } from '../theme/colors';
import { Header } from '../components/common/Header';

export const HelpSupportScreen: React.FC = () => {
  const handleCallCoastGuard = () => {
    Linking.openURL('tel:1554').catch(() => {});
  };

  const handleCallFisheriesHelpline = () => {
    Linking.openURL('tel:18004251660').catch(() => {});
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <Header showBackButton={true} title="Help & Support" />

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Emergency SOS Hotlines */}
        <View style={styles.emergencyCard}>
          <View style={styles.emergencyHeader}>
            <Text style={styles.sosEmoji}>🚨</Text>
            <View>
              <Text style={styles.sosTitle}>Marine Emergency Hotlines</Text>
              <Text style={styles.sosSubtitle}>Toll-free 24x7 maritime distress</Text>
            </View>
          </View>

          <TouchableOpacity
            style={styles.callButtonPrimary}
            onPress={handleCallCoastGuard}
            activeOpacity={0.8}
          >
            <Text style={styles.callBtnText}>📞 Indian Coast Guard: 1554</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={styles.callButtonSecondary}
            onPress={handleCallFisheriesHelpline}
            activeOpacity={0.8}
          >
            <Text style={styles.callSecBtnText}>
              📞 National Fisheries Distress Helpline
            </Text>
          </TouchableOpacity>
        </View>

        {/* FAQs */}
        <View style={styles.faqSection}>
          <Text style={styles.sectionTitle}>FREQUENTLY ASKED QUESTIONS</Text>

          <View style={styles.faqCard}>
            <Text style={styles.faqQuestion}>How does ORCA calculate safety?</Text>
            <Text style={styles.faqAnswer}>
              ORCA evaluates real-time wind gusts, significant wave heights, swell
              periods, and official IMD / INCOIS alerts to generate a clear
              decision (SAFE, CAUTION, DANGER, or BIPOD).
            </Text>
          </View>

          <View style={styles.faqCard}>
            <Text style={styles.faqQuestion}>What is a PFZ (Potential Fishing Zone)?</Text>
            <Text style={styles.faqAnswer}>
              PFZ hotspots are generated by satellite observations of sea surface
              temperature (SST) gradients and chlorophyll concentrations where fish
              shoals gather.
            </Text>
          </View>

          <View style={styles.faqCard}>
            <Text style={styles.faqQuestion}>Why does Madhya Pradesh show no marine data?</Text>
            <Text style={styles.faqAnswer}>
              Madhya Pradesh is an inland region without ocean coastline. ORCA
              specializes exclusively in marine fishing intelligence and coastal safety.
            </Text>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  emergencyCard: {
    backgroundColor: '#FEF2F2',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1.5,
    borderColor: '#FCA5A5',
    marginBottom: 20,
  },
  emergencyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  sosEmoji: {
    fontSize: 26,
    marginRight: 12,
  },
  sosTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.statusDanger,
  },
  sosSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 1,
  },
  callButtonPrimary: {
    backgroundColor: colors.statusDanger,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 8,
  },
  callBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  callButtonSecondary: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FCA5A5',
  },
  callSecBtnText: {
    color: colors.statusDanger,
    fontSize: 13,
    fontWeight: '600',
  },
  faqSection: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
    letterSpacing: 0.8,
    marginBottom: 10,
    marginLeft: 4,
  },
  faqCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.surfaceBorder,
  },
  faqQuestion: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 6,
  },
  faqAnswer: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 19,
  },
});
